name: Rebase Upstream
on:
  schedule:
    - cron: "0 0 * * 0" # run once a week
  workflow_dispatch:    # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 100
      - uses: imba-tjd/rebase-upstream-action@master
        with:
          branch: main
          upstream: prettier/prettier
